-- Table: public.warrantys

-- DROP TABLE IF EXISTS public.warrantys;

CREATE TABLE IF NOT EXISTS public.warrantys
(
    warranty_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    patientname character varying COLLATE pg_catalog."default",
    patientphonenumber character varying COLLATE pg_catalog."default",
    clinnic character varying COLLATE pg_catalog."default",
    labname character varying COLLATE pg_catalog."default",
    doctor character varying COLLATE pg_catalog."default",
    product character varying COLLATE pg_catalog."default",
    codenumber character varying COLLATE pg_catalog."default",
    expirationdate timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone,
    state smallint NOT NULL DEFAULT 1,
    CONSTRAINT warrantys_pk PRIMARY KEY (warranty_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.warrantys
    OWNER to postgres;
    -----------------------------------------------------------------------------

	-- Table: public.images

-- DROP TABLE IF EXISTS public.images;

CREATE TABLE IF NOT EXISTS public.images
(
    image_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    warranty_id integer,
    link character varying COLLATE pg_catalog."default",
    link_name character varying COLLATE pg_catalog."default",
    type character varying COLLATE pg_catalog."default",
    state smallint DEFAULT 1,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    created_by integer DEFAULT 0,
    CONSTRAINT image_pk PRIMARY KEY (image_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.installation_image
    OWNER to postgres;